In [36]:
#%load_ext autoreload    #### it has to appear on top of our code
#%autoreload 2

#read the file 
import pandas as pd

url = 'https://raw.githubusercontent.com/yveness7/IronHackIvet/main/Week_2/sharkattack!/sharks.csv'

sharks_df = pd.read_csv(url)






#after checking the contant of the columns
#we need to drop the columns that don't contain 
#info that we need or do now have values at all 


def drop_columns():
    
    sharks_df.drop("pdf", axis='columns',inplace=True)
    sharks_df.drop("href formula", axis='columns',inplace=True)
    sharks_df.drop("href", axis='columns',inplace=True)
    sharks_df.drop('Case Number', axis='columns',inplace=True)
    sharks_df.drop("Case Number.1", axis='columns',inplace=True)
    sharks_df.drop("original order", axis='columns',inplace=True)
    sharks_df.drop("Unnamed: 21", axis='columns',inplace=True)
    sharks_df.drop("Unnamed: 22", axis='columns',inplace=True)
    sharks_df.drop("Unnamed: 11", axis='columns',inplace=True)
    sharks_df.drop("Source", axis='columns',inplace=True)
    

    return sharks_df.columns



#fix the column names to lower case

def columns_lower():
    
    sharks_df.columns = sharks_df.columns.str.lower()
    
    return sharks_df.columns


#we remove rows with all Nan values


def drop_na():

sharks_df.dropna(how='all', inplace=True)

    return sharks_df


#after checking the number of missing values 
#using sharks_df.isna().sum() we start checking each 
#column independetly using .value_counts() and
#we want to fill the missing values in the 
#columns we have with 'N' to make the analysis 
#easier for now 


def fill_na():
    
sharks_df['state'].fillna('N',inplace=True)
sharks_df['location'].fillna('N',inplace=True)
sharks_df['injury'].fillna('N',inplace=True)
sharks_df['year'].fillna('N',inplace=True)
sharks_df['name'].fillna('N',inplace=True)
sharks_df['activity'].fillna('N',inplace=True)
sharks_df['time'].fillna('N',inplace=True)
sharks_df['age'].fillna('N',inplace=True)
sharks_df['species '].fillna('N',inplace=True)

    return sharks_df

#now we will start working with column 'type' to 
#narrow down the cagtegories for our analysis 

def activity_mapping():
    mapping = {
    
    'Invalid':'Unconfirmed',
    'Questionable':'Unconfirmed',
    'Sea Disaster':'Unconfirmed',
    'Unconfirmed':'Unconfirmed',    
    'N':'Unconfirmed',
    'Unverified':'Unconfirmed',
    'Under investigation':'Unconfirmed',
    '?':'Unconfirmed',
    'Boat':'Watercraft',
    'Watercraft':'Watercraft'
    
    }

    sharks_df['type'] = sharks_df['type'].replace(mapping)

    return sharks_df['type'] 

#we can check the new categories using sharks_df['type'].value_counts()
#and we narrowed them down to Unprovoked -5077, Unconfirmed - 836, Provoked - 632 & Watercraft - 361

#now we will work on the column 'injury'

def injury_cleaning():

    injuries_lambda = lambda x:'Injury' if isinstance(x, str) and any(keyword in x for keyword in ['foot',
                                                                                   'wounds','bitten',
                                                                                   'Lacerated','wound',
                                                                                    'Lacerations','Laceration',
                                                                                    'Abrasions','thigh',
                                                                                    'Injury','Bitten',    
                                                                                   'lacerated','bite',
                                                                                   'injury','laceration',
                                                                                    'injured','nipped',
                                                                                   'injuries','Injured',
                                                                                   'Left','Abrasion',
                                                                                   'Legs','gashed',
                                                                                    'Foot','bruised',
                                                                                    'drowning','Punctures',
                                                                                    'leg','knocked out',
                                                                                    'Leg', 'abraded','grazed',
                                                                                    'severed','lacerating',
                                                                                      'Survived','Scratches',         
                                                                                   'bitten']) else x


    sharks_df['injury'] = sharks_df['injury'].apply(injuries_lambda)

    fatal_lambda = lambda y:'Fatal' if isinstance(y, str) and any(keyword in y for keyword in ['FATAL','remains',
                                                                                          'Missing','Torso recovered',
                                                                                           'Drowned',
                                                                                          'Body not recovered',
                                                                                           'Recuers','Body found',
                                                                                           'Body recovered',
                                                                                           'consumed the body',
                                                                                           'bodies','Murdered',
                                                                                           'drowned',
                                                                                           'attacked sailors',
                                                                                           'Fatal'
                                                                                           
                                                                                           ]) else y
                                                                                        
    sharks_df['injury'] = sharks_df['injury'].apply(fatal_lambda)       


    unclear_lambda = lambda z:'Unclear' if isinstance(z, str) and any(keyword in z for keyword in ['No details','N',
                                                                                          'PROVOKED INCIDENT',
                                                                                           'unconfirmed',
                                                                                               'Non-fatal',
                                                                                               'Thought to',
                                                                                               'not confirmed',
                                                                                              'Recovered',
                                                                                              'Disappeared',
                                                                                               'Unknown'
                                                                                              
                                                                                              ]) else z



    sharks_df['injury'] = sharks_df['injury'].apply(unclear_lambda)
    
    return sharks_df['injury']

#if we use the following code
#injuries_series = sharks_df["injury"]
#injuries_series.value_counts(ascending=False).head()
#we narrowed down to the basic categories 
#Injury     5227
#Fatal      1126
#Unclear     273


#now we will fix the column 'activity'

def activity_clean():

    fishing_lambda = lambda i:'Fishing' if isinstance(i, str) and any(keyword in i for keyword in ['Spearfishing',
                                                                                      'Fishing ',
                                                                                               'Shark fishing',
                                                                                              'Surf fishing',
                                                                                               'Wade Fishing',
                                                                                               'Kayak Fishing',
                                                                                               'Crabbing',
                                                                                               'Wade-fishing',
                                                                                               'Wade fishing',
                                                                                              'Clamming',
                                                                                               'Crayfishing',
                                                                                               'Sculling',
                                                                                               'Shell diving'
                                                                                               
                                                                                           
                                                                                   ]) else i


    sharks_df['activity'] = sharks_df['activity'].apply(fishing_lambda) 


    swimming_lambda = lambda o:'Swimming' if isinstance(o, str) and any(keyword in o for keyword in ['Wading',
                                                                                               'Bathing',
                                                                                               'Standing',
                                                                                               'Swimming ',
                                                                                                 'Scuba diving',
                                                                                                 'Floating',
                                                                                                 'Jumped overboard',
                                                                                                 'Jumping',
                                                                                                 'Boat swamped',
                                                                                                 'Splashing',
                                                                                                 'Kayaking / Fishing',
                                                                                                 'Seine netting',
                                                                                                 'Dangling feet in the water',
                                                                                                 'Kayak fishing',
                                                                                                 'Jumped into the water',
                                                                                                 'Freedom Swimming',
                                                                                                 'Freedom swimming'
                                                                                                 
                                                                                         
                                                                                   ]) else o
    sharks_df['activity'] = sharks_df['activity'].apply(swimming_lambda) 
    
    diving_lambda = lambda p:'Scuba Diving' if isinstance(p, str) and any(keyword in p for keyword in ['Diving',
                                                                                               'Pearl diving',
                                                                                               'Sponge diving',
                                                                                                   'Hard hat diving',
                                                                                                   'Skindiving',
                                                                                                   'SCUBA diving'
                                                                                               
                                                                                   ]) else p
    sharks_df['activity'] = sharks_df['activity'].apply(diving_lambda) 



    walking_lambda = lambda w:'Walking' if isinstance(w, str) and any(keyword in w for keyword in ['Treading water',
                                                                                       'Standing','Playing',
                                                                                               'Walking out of the water after surfing'
                                                                                               
                                                                                   ]) else w
    sharks_df['activity'] = sharks_df['activity'].apply(walking_lambda) 


    surfing_lambda = lambda k:'Surfing' if isinstance(k, str) and any(keyword in k for keyword in ['Body boarding',
                                                                                       'Body surfing',
                                                                                               'Skin diving',
                                                                                               'Boogie boarding',
                                                                                              'Boogie Boarding',
                                                                                               'Surf-skiing',
                                                                                               'Surf skiing',
                                                                                               'Sitting on surfboard',
                                                                                               'Surfing ',
                                                                                               'Surfing, paddling seawards',
                                                                                               'Body Surfing',
                                                                                               'Paddling on surfboard',
                                                                                               'Paddling',
                                                                                               'Body-boarding',
                                                                                               'Paddleskiing',
                                                                                               'Body Boarding',
                                                                                               'Paddle boarding',
                                                                                               'Kite Surfing',
                                                                                               'Kite surfing',
                                                                                               'Stand-Up Paddleboarding'

                                                                                              ]) else k
    sharks_df['activity'] = sharks_df['activity'].apply(surfing_lambda) 









    freediving_lambda = lambda q:'Free Diving' if isinstance(q, str) and any(keyword in q for keyword in ['Freediving',
                                                                                            'Free diving for abalone',
                                                                                                      'Free diving'

                                                                                              ]) else q
    sharks_df['activity'] = sharks_df['activity'].apply(freediving_lambda) 

    accident_lambda = lambda a:'Accident' if isinstance(a, str) and any(keyword in a for keyword in ['Fell overboard',
                                                                                                    'Fell into the water',
                                                                                                    'Sea disaster',
                                                                                                 'Sea Disaster',
                                                                                                 'Knocked overboard',
                                                                                                 'Shipwreck',
                                                                                                 'Murder',
                                                                                                 'Wreck of the schooner Pohoiki',
                                                                                                 'boat capsized',
                                                                                                 'Suicide'
                                                                                                    

                                                                                              ]) else a
    sharks_df['activity'] = sharks_df['activity'].apply(accident_lambda) 

    unknown_lambda = lambda un:'Unknown' if isinstance(un, str) and any(keyword in un for keyword in ['N','.']) else un
                                                                    
    sharks_df['activity'] = sharks_df['activity'].apply(unknown_lambda) 

    other_lambda = lambda t:'Various' if isinstance(t, str) and any(keyword in t for keyword in ['Shark watching',
                                                                                             'Feeding fish',
                                                                                             'Shark watching',
                                                                                             'Lifesaving drill',
                                                                                             'Feeding sharks',
                                                                                             'Tagging sharks',
                                                                                             'SUP','Boat',
                                                                                             'Watercraft',
                                                                                             'Sitting on gunwale of boat',
                                                                                             'Competing in the Woodvale Atlantic Rowing Race',
                                                                                         'Escaping from Alacatraz',
                                                                                             'Sitting'
                                                                                            ]) else t
                                                                    
    sharks_df['activity'] = sharks_df['activity'].apply(other_lambda) 

    return sharks_df['activity']

#now we narrowed down the column 'activity' to 14 basica categories 
"""Swimming        1900
Surfing         1448
Fishing         1153
Unknown          681
Scuba Diving     429
Accident         131
Snorkeling       127
Walking           89
Various           74
Kayaking          39
Windsurfing       20
Canoeing          16
Rowing            12
Sailing            9"""


#now we want to clean the 'sex' column

def gender_clean():
    gender_mapping = {
    'M':'M',
    'N':'N',
    'lli':'N',
    'M x 2':'M',    
    ' M':'M',
    '.':'N',
    'M ':'M'
}

    sharks_df['sex'] = sharks_df['sex'].replace(gender_mapping)


#and we have the categories 'M for male, 'F' for female and 'N' - no answer 



    return sharks_df['sex']

In [37]:
sharks_df

,date,year,type,country,state,location,activity,name,sex,age,injury,time,species
0,15 Oct-2023,2023.0,Unprovoked,USA,Hawaii,"Hanalei Bay, Kauai",Surfing,Kevin Kanehe,M,50,Injury,16h00,"Tiger shark, 12' to 15'"
1,13 Oct-2023,2023.0,Unconfirmed,USA,California,"Linda Mar, Pacific State Beach, San Mateo County",Surfing,male,M,52,Injury,15h45,N
2,02 Oct-2023,2023.0,Unprovoked,USA,Hawaii,"Paia, Maui",Surfing,K. Cole,F,45,Injury,13h00,N
3,01 Oct-2023,2023.0,Unprovoked,AUSTRALIA,South Australia,Beachport,Swimming,Pamela Cook,F,64,Injury,07h45,N
4,01 Oct-2023,2023.0,Unprovoked,USA,California,"Wildcat Beach, Marin County",Swimming,Felix Louis N'Jai,M,52,Fatal,10h40,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6901,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Scuba Diving,male,M,N,Fatal,N,N
6902,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,N,Scuba Diving,Ahmun,M,N,Fatal,N,N
6903,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,N,Fatal,N,N
6904,1883-1889,0.0,Unprovoked,PANAMA,N,"Panama Bay 8ºN, 79ºW",Unknown,Jules Patterson,M,N,Fatal,N,N
6905,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,Fatal,N,N

In [38]:
sharks_df["injury"].value_counts(ascending=False).head(60)

Injury                                                                                                                                                                                                                                     5244
Fatal                                                                                                                                                                                                                                      1129
Unclear                                                                                                                                                                                                                                     253
It is probable that all onboard (2 men & 2 women) died when the plane crashed into the sea & her body was scavenged by a shark                                                                                                                1
Swimfin & 2 wool socks removed by shark, suit torn                                                                                                                                                                                            1
Injuries not caused by sharks                                                                                                                                                                                                                 1
Injuries caused by coral, not the  shark                                                                                                                                                                                                      1
Boat damaged                                                                                                                                                                                                                                  1
Boat followed shark; shark holed boat                                                                                                                                                                                                         1
Body recovery efforts were hampered by large sharks but sharks did not cause the deaths.                                                                                                                                                      1
As searchers approached wreckage, sharks circled one canoe & seized oar from another.                                                                                                                                                         1
Shark bumped him                                                                                                                                                                                                                              1
Minor cuts & bruises on face & neck                                                                                                                                                                                                           1
Right buttock slashed                                                                                                                                                                                                                         1
1  survivor                                                                                                                                                                                                                                   1
Knee ripped to bone                                                                                                                                                                                                                           1
Lost left arm                                                                                                                                                                                                                                 1
One body sighted but not recovered due to shark activity                                                                                                                                                                                      1
Shark rammed boat, breaching its hull                                                                                                                                                                                                         1
Shark rammed boat & bit transom                                                                                                                                                                                                               1
"Molested by shark that nibbled his bare feet",  rescued 30 hours later.                                                                                                                                                                      1
Shark's fin caused abrasion on his chest                                                                                                                                                                                                      1
Buttock removed                                                                                                                                                                                                                               1
Shark jumped from sea, taking fish & his right arm                                                                                                                                                                                            1
U.S. destroyer John W. Weeks, 6 miles offshore, demonstrating guns & bombs for Mexican officials was thought to have driven the shark into the shallows where it bit the bather before other bathers drove it away with sticks & clubs.       1
Human hand recovered from 2.4 m [8'] tiger shark                                                                                                                                                                                              1
2 hours later shark bit Jeppsen’s feet, arm, knee & finally killed him. Tony, clothing torn but alive, washed ashore on Cuban coast                                                                                                           1
Kneecap removed                                                                                                                                                                                                                               1
Suit ripped                                                                                                                                                                                                                                   1
Shark jumped into cockpit                                                                                                                                                                                                                     1
Radius & ulna bared                                                                                                                                                                                                                           1
Shark holed and sank boat, occupants rescued                                                                                                                                                                                                  1
About 300  crew perished during the sinking, the remainder abandoned ship. Many who survived the loss of the ship were taken by sharks. In all, only 316 of her crew of 1,196 survived.                                                       1
When survivors werer rescued on 10/27/1944 by PC 623 there were many sharks in the area                                                                                                                                                       1
When picked up by the USS Boyd DD 44 on 6/23/1944 his raft was "surrounded by sharks"                                                                                                                                                         1
Of the 1,429 people on board, only 448 survived. Sharks were attacking survivors as they were being rescued                                                                                                                                   1
Apparently went missing while diving. Helicopter searching for him spotted school of sharks attacking a "white object" 15' below the surface                                                                                                  1
3 of the 4 passengers killed by sharks                                                                                                                                                                                                        1
3 were lost, 3 survived                                                                                                                                                                                                                       1
Shark leapt into boat, hitting Fanie Schoeman on his back before sliding into the sea                                                                                                                                                         1
Swim fins badly torn by the shark's teeth                                                                                                                                                                                                     1
Swept out to sea,  5.5 m [18'] shark seen in the vicinity, body not recovered.                                                                                                                                                                1
8 to 10 puncture marks around knee                                                                                                                                                                                                            1
Shark bit rudder & hull                                                                                                                                                                                                                       1
The press reported this as an attack by a white shark but the diver was the agressor                                                                                                                                                          1
Cracked jaw & broken tooth, shark took chunk out of surfboard                                                                                                                                                                                 1
Shark breached hull of boat                                                                                                                                                                                                                   1
Considered a doubtful incident                                                                                                                                                                                                                1
Shark following hooked fish, rammed & holed boat                                                                                                                                                                                              1
Shark jumped in boat, hitting her in the face & knocking her unconscious                                                                                                                                                                      1
"lost part of a finger"                                                                                                                                                                                                                       1
It was believed that survivors were killed by sharks                                                                                                                                                                                          1
Shark leapt into boat, pinning Mamacos beneath and fracturing his pelvis, then trashed the boat rendering it inoperable                                                                                                                       1
Several broken ribs                                                                                                                                                                                                                           1
Shark leapt into boat, landed on Hlope's back, then bit his left forearm                                                                                                                                                                      1
Remains recovered days later from shark                                                                                                                                                                                                       1
Shark bumped Colleen, the nudged Scott, then bit Frisbee & swam away with it                                                                                                                                                                  1
Bumped shoulder, bit head                                                                                                                                                                                                                     1
Passengers taken by sharks                                                                                                                                                                                                                    1
Bones and brightly colored bangles recovered  3.35 m, 145.5-kg tiger shark’s gut                                                                                                                                                              1
Name: injury, dtype: int64

In [11]:
sharks_df.describe()

,date,year,type,country,state,location,activity,name,sex,age,injury,time,species
count,6906,6906.0,6888,6856,6906,6906,6906,6906,6327,6906,6906,6906,6906
unique,5937,258.0,4,223,893,4483,748,5659,3,170,432,408,1667
top,1957,2015.0,Unprovoked,USA,Florida,N,Swimming,male,M,N,Injury,N,N
freq,11,143.0,5077,2533,1177,564,1900,671,5555,2986,5244,3519,3120

,date,year,type,country,state,location,activity,name,sex,age,injury,time,species
count,6906,6906.0,6888,6856,6906,6906,6906,6906,6327,6906,6906,6906,6906
unique,5937,258.0,4,223,893,4483,748,5659,3,170,432,408,1667
top,1957,2015.0,Unprovoked,USA,Florida,N,Swimming,male,M,N,Injury,N,N
freq,11,143.0,5077,2533,1177,564,1900,671,5555,2986,5244,3519,3120

In [ ]:
##### Exploratory Data Analysis (EDA) #####

# Summary for numerical variables
sharks_df.describe()
# Summary for categorical variables
sharks_df.describe(include=["O"])

##### visualization #####

#### For continuous variables: Histogram
sns.histplot(sharks_df['Age'], bins=100)

#### For categorical or discrete variables

# Bar chart of injury
sns.countplot(x='Injury', data=sharks_df)

# Scatterplot for numerical variables
sns.scatterplot(x = "Age", y = "Year", data = sharks_df)


#### Relationship between variables
sns.scatterplot(x = "Injury", y = "Activity", data = sharks_df)


# Calculate the correlation matrix for numerical variables
corr_matrix = sharks_df.corr()
corr_matrix


# Plot a heatmap for numerical variables
sns.heatmap(corr_matrix, annot=True)